// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOZ1WihM7oIX03NXsL_1uLfpy6CnOX6xQ',
    appId: '1:254417929082:web:514bfb4fb6e7923e7cccc3',
    messagingSenderId: '254417929082',
    projectId: 'appecommerce-13113',
    authDomain: 'appecommerce-13113.firebaseapp.com',
    storageBucket: 'appecommerce-13113.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApYe3Hyoyb_tC2dkWWaITJ8978_9oPyVU',
    appId: '1:254417929082:android:2ddbbd836e6f4b687cccc3',
    messagingSenderId: '254417929082',
    projectId: 'appecommerce-13113',
    storageBucket: 'appecommerce-13113.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrqg8DNcNLxKaHkB9qfbKT2E7obWKq3Q',
    appId: '1:254417929082:ios:419ea1c1c8da777c7cccc3',
    messagingSenderId: '254417929082',
    projectId: 'appecommerce-13113',
    storageBucket: 'appecommerce-13113.firebasestorage.app',
    iosBundleId: 'com.example.appecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfrqg8DNcNLxKaHkB9qfbKT2E7obWKq3Q',
    appId: '1:254417929082:ios:419ea1c1c8da777c7cccc3',
    messagingSenderId: '254417929082',
    projectId: 'appecommerce-13113',
    storageBucket: 'appecommerce-13113.firebasestorage.app',
    iosBundleId: 'com.example.appecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOZ1WihM7oIX03NXsL_1uLfpy6CnOX6xQ',
    appId: '1:254417929082:web:58cb643e9e9614f97cccc3',
    messagingSenderId: '254417929082',
    projectId: 'appecommerce-13113',
    authDomain: 'appecommerce-13113.firebaseapp.com',
    storageBucket: 'appecommerce-13113.firebasestorage.app',
  );
}
